### ISSUE TITLE
Make token management reusable?

### ISSUE THREAD

**Issue by andig** [uhthomas/tesla_exporter#7] opened 2021-01-30 11:22 UTC
I'm author of [evcc](https://github.com/andig/evcc) (MIT license) and coming from https://github.com/timdorr/tesla-api/issues/215 and https://github.com/andig/evcc/issues/624. 

I'm currently using https://github.com/jsgoecke/tesla/issues/38 which doesn't support the MFA yet. 

It would be great to regain access to the Tesla data for evcc users. However I would prefer to do so without having users to run a Prometheus exporter. Would you consider opening API for external consumption (i.e. remove the `internal` path restriction) or provide a subset API for token handling?

I have a bunch of other car APIs implemented in go I could offer "in return", maybe for something like an universal exporter? If you want to discuss feel free to reach out at cpuidle@gmx.de

**Comment by uhthomas** [comment] 2021-01-30 18:35
Yep! That sounds like a good idea to me. I wrote `internal/tesla` specifically to support MFA, but didn't make it its own package as it was quite experimental and didn't want to commit to non-breaking changes. Can create a new repository and move it there, but will need to some modifications to do token refreshing and such.

**Comment by andig** [comment] 2021-01-31 09:27
> Can create a new repository and move it there, but will need to some modifications to do token refreshing and such.

Sounds great, thank you for the quick response! I've already prototyped with a copy at https://github.com/andig/evcc/pull/626 and would like to share some thoughts:

- I wasn't able to pass user/password/passcode at once since the passcode- as I understand- is only generated during the login session. Solved by using a channel (or a callback) for the passcode in [https://github.com/andig/evcc/pull/626/files](https://github.com/andig/evcc/pull/626/files#diff-c1fb40e8a0841cbaae554ff0d949e97c4d94c50bcee6ffc8675086a30a1ef591R30). Unsure how that works for you, I'm probably not getting a core point here.
- successfully tested MFA, have not yet testet non-MFAed accounts
- token refresh is definitely needed. In other adapters I have something like a `Token()` method that will always return a refreshed token. Need to rethink how to do that with MFA (does refreshing trigger the device?).
- it would be good to be able to inject my own `HTTPDoer` or `Transport/RoundTripper` for sake of logging.
- no `Print(ln)s`

I'd be happy to provide the adapter to `jsgoecke/tesla` and test, please let me know if I can contribute anything else.

**Comment by andig** [comment] 2021-01-31 21:26
Also note these two linter warnings (line numbers are wrong), but they speak for themselves:

```
❯ make lint
golangci-lint run
vehicle/tesla/client.go:288:3: structtag: struct field tag `json:"data` not compatible with reflect.StructTag.Get: bad syntax for struct tag value (govet)
                Data struct {
                ^
vehicle/tesla/client.go:180:12: SA1019: goquery.NewDocumentFromResponse is deprecated: Use goquery.NewDocumentFromReader with the response's body. (staticcheck)
        d, err := goquery.NewDocumentFromResponse(res)
                  ^
```

**Comment by uhthomas** [comment] 2021-01-31 21:32
Great work! This is my fault for not using vet, hah. I'll make some fixes and such now.

**Comment by uhthomas** [comment] 2021-02-01 00:32
Just to keep my line of through in writing, I'm pretty sure this code can be slimmed down a lot. It looks like it should be (mostly) compatible with [golang/oauth2](https://github.com/golang/oauth2). Will experiment tomorrow and commit the results to [uhthomas/tesla](/uhthomas/tesla)

**Comment by uhthomas** [comment] 2021-02-01 01:07
Annoyingly, Tesla rejects any redirect URLs which are not `https://auth.tesla.com/void/callback` . Not really sure what to do about this, but my suspicion that it should _mostly_ work with the oauth2 package is seeming to be correct.

Will take a look tomorrow and see if I can't find a way to fix that redirect URL... thing.

**Comment by uhthomas** [comment] 2021-02-01 01:34
So, intercepting the URL redirect from the Chrome developer console, and manually pasting the code provided in the callback URL works, thankfully. It's confirmed that `auth.tesla.com` implement the oauth2 spec correctly (thank god). The only problem is the redirect URL. Literally anything other than `https://auth.tesla.com/void/callback` just doesn't work.

I've committed my findings up until now, which again mostly works. I hope this is useful and we can figure out together how to get round this issue.

[uhthomas/tesla/cmd/login](https://github.com/uhthomas/tesla/blob/8063ad68efe2178f87d4110300737df883adbab2/cmd/login/main.go)

**Comment by uhthomas** [comment] 2021-02-01 02:01
Have also just discovered
```go
c := &oauth2.Config{
	ClientID:     "teslaweb",
	ClientSecret: "",
	RedirectURL:  "https://www.tesla.com/openid-connect/generic",
	Scopes:       []string{"openid email profile"},
	Endpoint: oauth2.Endpoint{
		AuthURL:  "https://auth.tesla.com/oauth2/v3/authorize",
		TokenURL: "https://auth.tesla.com/oauth2/v3/token",
	},
}
```

So, there's `ownerapi` and `teslaweb`.

**Comment by andig** [comment] 2021-02-01 07:21
I have not used oauth2 yet and the rewrite leaves me confused: the code endpoint it on the Tesla website now and no longer in the client code? Maybe that's not a bad idea at all...

**Comment by andig** [comment] 2021-02-01 09:30
I also have the non-MFA `authenticate()` method working where you'll get the code directly and don't need to go through the authentication devices:

	func (c *Client) authenticate(ctx context.Context, username, password string) (transactionID, code string, err error) {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, c.authURL().String(), nil)
		if err != nil {
			return "", "", fmt.Errorf("new request: %w", err)
		}
		req.Header.Set("User-Agent", "tesla_exporter")

		res, err := c.c.Do(req)
		if err != nil {
			return "", "", fmt.Errorf("do: %w", err)
		}
		defer res.Body.Close()

		if res.StatusCode != http.StatusOK {
			return "", "", fmt.Errorf("unexpected status code %d", res.StatusCode)
		}

		d, err := goquery.NewDocumentFromReader(res.Body)
		if err != nil {
			return "", "", fmt.Errorf("new document: %w", err)
		}

		v := url.Values{
			"identity":   {username},
			"credential": {password},
		}

		d.Find("input[type=hidden]").Each(func(_ int, s *goquery.Selection) {
			name, ok := s.Attr("name")
			if !ok {
				return
			}
			value, ok := s.Attr("value")
			if !ok {
				return
			}
			v.Set(name, value)
		})

		cr := c.c.CheckRedirect
		c.c.CheckRedirect = func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		}
		defer func() { c.c.CheckRedirect = cr }()

		req, err = http.NewRequestWithContext(ctx, http.MethodPost, c.authURL().String(), strings.NewReader(v.Encode()))
		if err != nil {
			return "", "", fmt.Errorf("new request: %w", err)
		}
		req.Header.Set("User-Agent", "tesla_exporter")
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

		res, err = c.c.Do(req)
		if err != nil {
			return "", "", fmt.Errorf("do: %w", err)
		}
		defer res.Body.Close()

		if res.StatusCode == http.StatusFound {
			fmt.Println("MFA not enabled")

			u, err := url.Parse(res.Header.Get("Location"))
			if err != nil {
				return "", "", fmt.Errorf("do: %w", err)
			}

			return "", u.Query().Get("code"), nil
		}

		if res.StatusCode != http.StatusOK {
			return "", "", fmt.Errorf("unexpected status code %d", res.StatusCode)
		}

		return v.Get("transaction_id"), "", nil
	}

That won't fit with the oauth2 package, will it?

**Comment by uhthomas** [comment] 2021-02-01 10:10
> I have not used oauth2 yet and the rewrite leaves me confused: the code endpoint is on the Tesla website now and no longer in the client code? Maybe that's not a bad idea at all...

Yeah, this is how the oauth2 flow is intended to work. There are lots of examples, but the most solid I've seen is [Google's YouTube sample](https://github.com/youtube/api-samples/blob/master/go/oauth2.go). It's a little convoluted but the gist is that most of it is done in-browser.

This will not be possible at all with Tesla as they own the client IDs and client secrets. The only way to do this is to:
* Use the standard OAuth2 flow where possible
* Emulate what a browser _would_ be doing, which is essentially what was being done before.

I'll get a prototype working today. It should be quite easy to swap MFA in/out too.

**Comment by andig** [comment] 2021-02-01 10:43
Here's the code that includes the non-MFA version: https://github.com/andig/evcc/pull/626/files#diff-3dedd39b9e44f08556049a8f60f7a6a0c1e007b288375afe53c480f77a73217a. Using callback to get the code in case of MFA.

**Comment by andig** [comment] 2021-02-01 10:45
> Emulate what a browser would be doing, which is essentially what was being done before.

Understand that part. It's basically what I'm doing all over the place with https://github.com/andig/evcc/tree/master/vehicle to emulate the vendor apps.

> I'll get a prototype working today.

Waiting impatiently ;)

**Comment by uhthomas** [comment] 2021-02-01 13:26
@andig I've rewritten the code and hopefully it makes clear what I mean by having a hybrid. It uses the native OAuth flow, but then deviates to emulate Tesla's browser-based login. It's a little strange, but it's much cleaner and more sensical than before. Let's work together to break this down and make it more composable.

As it's using the native OAuth flow, token refreshing is not a concern. There unfortunately _has_ to be user intervention for the initial exchange, and it has to be controlled by us, not Tesla.

See [uhtomas/tesla@8d67b43e03710dbe2ce672aa50ee776b37d67130](https://github.com/uhthomas/tesla/commit/8d67b43e03710dbe2ce672aa50ee776b37d67130)

**Comment by uhthomas** [comment] 2021-02-01 13:28
Oh - this should also be good for non-MFA setups too, and also MFA with multiple devices. Give it a try!

**Comment by andig** [comment] 2021-02-01 15:42
Couple of observations, I'm still not sure if I fully understand the approach:
- module name is wrong (`github.com/uhthomas/thomas` vs `tesla`). Instead of `tesla`, maybe `teslaauth`?
- non-MFA is not working, you're not excluding the MFA device in your flow (See https://github.com/andig/evcc/pull/626/files#diff-3dedd39b9e44f08556049a8f60f7a6a0c1e007b288375afe53c480f77a73217aR194 which seems to work for me). I can provide a PR if you want.

      Password:          
      2021/02/01 16:26:09 do: Post "https://auth.tesla.com/void/callback?code=...: net/http: timeout awaiting response headers
      exit status 1

- `cmd/login/login.go` should not be inside the `cmd` folder but top-level?
- the code prompt should be a callback that applications can implement as needed
- the oauth flow is for `auth.tesla.com`? Where is the exchange into an owners api token handled and how do we notice when that expires?

**Comment by uhthomas** [comment] 2021-02-01 15:57
Thanks for the feedback - this was mostly just an initial stab at reducing the scope of code and to let the official OAuth2 package handle the appropriate OAuth 2 stuff. It also mostly demonstrates where we have to break out of the flow in order to emulate what a user would be doing inside a browser.

I'm not entirely sure what direction to take with breaking this out, as the initial token exchange requires user input, due to MFA. I'll work on making a nice API to break it up into the individual components:
* Username
* Password
* Device selector
* Passcode

Any suggestions would be much appreciated.

I can confirm that the token does not need to be exchanged via the legacy owner API. Requests work as expected using v3 OAuth2 tokens.

I'm happy that we've been able to demonstrate that Tesla's v3 API is OAuth2 compliant. Let's finish the job by making it reusable.

**Comment by andig** [comment] 2021-02-01 16:09
> Thanks for the feedback - this was mostly just an initial stab at reducing the scope of code and to let the official OAuth2 package handle the appropriate OAuth 2 stuff. It also mostly demonstrates where we have to break out of the flow in order to emulate what a user would be doing inside a browser.

Hope I don't come across as complaining. I'm just toooooo impatient ;) It's absolutely great to see this interact with the OAuth package and I'll need to analyse how to do this for my other auth tasks across the various vehicle apis.

> I'll work on making a nice API to break it up into the individual components. I'm not entirely sure what direction to take with breaking this out, as the initial token exchange requires user input, due to MFA. 

Not always. If user has not enabled MFA you'll get the token without. We should support both flows.

> Any suggestions would be much appreciated.

- Username/Password: wouldn't we always need those (or be supplying initial access/refresh token to pick up)?
- Device selector/passcode: could both be callbacks, for selector augmented with library capabilities

> Let's finish the job by making it reusable.

If its ok I'll continue following your progress and just try to use in my scenario.

**Comment by uhthomas** [comment] 2021-02-01 16:29
Aha, not a problem 😄   It's good to see enthusiasm.

You're right that the `username` and `password` are always required. I imagine it might even be easier to make the device selection and passcode obtaining the same thing. Something like
```go
type DeviceSelector struct {
        SelectDevice(ctx context.Context, devices []Device) (d Device, passcode string, err error)
}
```

Or even
```go
type DeviceVerifier struct {
      VerifyDevice(ctx context.Context, devices []Device) error
}

// impl

func VerifyDevice(ctx context.Context, devices []Device) error {
    return devices[0].Verify(ctx, "123456")
}
```

Let me know your thoughts. I'll sit on it for a little bit, but will ultimately try to provide something that works, even if it isn't perfect.

**Comment by andig** [comment] 2021-02-01 16:55
I like the API. If you need selection though it would be good if users could have a choice of configuring up-front. With this api they will only see the devices during the login but have no chance upfront?

**Comment by uhthomas** [comment] 2021-02-01 17:03
Unfortunately we don't know what devices exist upfront, so that is the only option really.

**Comment by andig** [comment] 2021-02-01 18:46
No problem. Need to prompt the user anyway for the code, so he can chose his device then.

**Comment by uhthomas** [comment] 2021-02-02 21:22
Thanks for your patience @andig.

I've written a usable API for logging in in [this commit](https://github.com/uhthomas/tesla/commit/8f97ef33b7b36f06f47d01968570c90920afc166). It's not perfect, but it should be a solid start. The [login](https://github.com/uhthomas/tesla/blob/master/cmd/login/main.go) tool is using it and it seems to work fine. It would be great to get some feedback 😄

**Comment by andig** [comment] 2021-02-03 07:46
Looks great, will try later today. Some ideas:
- expose `state` and `pkce` for library consumers as the exact format matters
- expose factory for the Oauth config and tesla.Auth (or wrap both into convenience method)
- useragent might be configurable for consumers
- and:


		switch res.StatusCode {
		case http.StatusOK:
		case http.StatusFound:
			return codeFromResponse(res)
		}


is really

        if res.StatusCode == http.StatusFound { return }

Will update once tested :)

**Comment by uhthomas** [comment] 2021-02-03 13:26
Good points - I can take a look at those this evening.

Have fixed the status code thing, that's my bad.

Glad to hear it works well for you, hopefully with the upcoming improvements it should be a little more graceful also.

**Comment by uhthomas** [comment] 2021-02-03 13:28
I intend to build out the actual API too, mostly porting what already exists in [intrnal/tesla](https://github.com/uhthomas/tesla_exporter/tree/main/internal/tesla). It should be a nice all-in-one at some point.

**Comment by andig** [comment] 2021-02-03 13:41
It seems that https://github.com/jsgoecke/tesla isn‘t receiving much attention anymore, so that would be great! For time being I‘ve patched the two together...

**Comment by andig** [comment] 2021-02-09 10:12
Seems implementation is pretty much ready. Regarding PKCE, I've happened to stumble across https://github.com/nirasan/go-oauth-pkce-code-verifier which might be usable instead of exporting more functions.

Shall we move the remaining discussion- except for any open points you might want to fix- to the target repo?

One last idea: if you're interested in supporting more vehicles as part of tesla_exported you could look at the vehicle implementations from evcc. It is only focused on soc, range and charging time though.

**Comment by andig** [comment] 2021-02-09 11:00
Here's a minimum reusable pkce verifier (found link above not too helpful):

	import (
		"crypto/rand"
		"crypto/sha256"
		"encoding/base64"
		"io"
	)

	// PKCE implements Proof Key for Code Exchange
	type PKCE []byte

	// New creates PKCE using crypto/rand
	func New(length int) (*PKCE, error) {
		pkce := make(PKCE, length)
		_, err := io.ReadFull(rand.Reader, pkce[:])
		return &pkce, err
	}

	// Challenge is the SHA256 challenge digest in base64 encoding
	func (p *PKCE) Challenge() string {
		b := sha256.Sum256(*p)
		return base64.RawURLEncoding.EncodeToString(b[:])
	}

	// Verifier is the challenge in base64 encoding
	func (p *PKCE) Verifier() string {
		return base64.RawURLEncoding.EncodeToString(*p)
	}

As it's really your code- not sure if you'd want to publish as separate package?

**Comment by uhthomas** [comment] 2021-02-09 13:48
Thanks a ton again for all the interest and support with this. I think you're right, it would be a good idea to move this issue over to the target repo.

In regard to PKCE: Do we even need to expose it? There's not really any configuration which can be done. I'm thinking we just export a function to create the OAuth client which handles all of this.

**Comment by andig** [comment] 2021-02-10 12:11
> In regard to PKCE: Do we even need to expose it? 

Good point. I realize I actually have a higher-level API (https://github.com/andig/evcc/blob/master/vehicle/tesla/client.go) that provides the following:
- perform login or create `TokenSource` from existing token
- set security device handler
- inject custom client for logging (at least for the auth exchange, preferable would be for the token source or a token client, too)

Might as well export such a client as higher level API?

**Comment by bogosj** [comment] 2021-02-10 23:02
I for one would love to see a wrapper that simplifies this. Using https://github.com/uhthomas/tesla/tree/master/cmd/login and getting a JSON blob that looks like this:

{
        "access_token": "<redacted>",
        "token_type": "Bearer",
        "refresh_token": "<redacted>",
        "expiry": "2021-02-10T17:45:14.968711331-05:00"
}

If we had a library that took this JSON string and handled the OAuth setup and provided a method to make API calls to GET or POST data to the endpoints https://tesla-api.timdorr.com/ would be great.

**Comment by uhthomas** [comment] 2021-02-10 23:11
I think that's a good idea. I intend to make [uhthomas/tesla](https://github.com/uhthomas/tesla] a fully-fledged Tesla client API, but have been really busy at work.

**Comment by bogosj** [comment] 2021-02-11 04:35
OK, I don't *think* a lot of work needs to be done. I've taken your `newOAuth2Client` method and used it to create a new HTTP client. I've then used the jsgoecke/tesla library and just shim'd the client in. Instead of calling the NewClient() function provided I've created a simple struct passing that client in as the HTTP field, set that client on the module-level variable, and everything seems to work with no modification.

```go
oc, err := newOAuth2Client(context.Background(), c.OAuthConfigPath, c.OAuthTokenPath)
if err != nil {
    log.Fatal(err)
}
client := &tesla.Client{HTTP: oc}
tesla.ActiveClient = client
return client
```

**Comment by bogosj** [comment] 2021-02-11 04:52
This definitely works for me. https://github.com/bogosj/go-tesla-go/commit/0734ca75a1aaca030779f96ebdee98c1483b03e0 brought my project back to life with zero change to the usage of jsgoecke's library.

Thank you!

**Comment by andig** [comment] 2021-02-11 07:29
> This definitely works for me. bogosj/go-tesla-go@0734ca7 brought my project back to life with zero change to the usage of jsgoecke's library.

I'm using the same approach in https://github.com/andig/tesla but made it a bit more complex by passing in a token source.

@bogosj are you willing to fork and maintain jsgeocke? There are a couple of other changes like 64bit VINs that have been hanging around for a long time.

**Comment by bogosj** [comment] 2021-02-20 02:04
https://github.com/bogosj/tesla/issues/8 if you have thoughts on how to adapt the existing library to handle OAuth.

**Comment by andig** [comment] 2021-02-24 08:08
> I think that's a good idea. I intend to make uhthomas/tesla a fully-fledged Tesla client API, but have been really busy at work.

@uhthomas there is work going on at [bogosj/tesla](https://github.com/bogosj/tesla) for forking jsgoecke (unmaintained). Do you have plans for wrapping up the remaining pieces of the login API?

**Comment by uhthomas** [comment] 2021-02-25 22:15
@andig @bogosj What would you like to see for the login API? Have done some work to this repo and the `uhthomas/tesla` repo to get OAuth2 working in a sensible manner.

**Comment by bogosj** [comment] 2021-02-25 22:26
It seems we only really need the token struct. I'd think a flag to cmd/login that writes the token struct to json at a provided path would make it slightly easier for people to use. You can see the NewClientFromTokenFile function in https://github.com/bogosj/tesla.

Also FWIW I was trying to get a token a day or two ago using cmd/login and was getting a *lot* of timeouts. At the same time I was able to very quickly get a token using https://teslascope.com/help/generating-tokens. Not sure if it was just timing on my part or something w.r.t. how the go code was timing out on the HTTP requests...

**Comment by uhthomas** [comment] 2021-02-25 23:50
That sounds reasonable -- will add that tomorrow 😃 

I think there's something odd going on with Tesla and their API at the moment. It looks like AkamiGHost is blocking lots of requests. FWIW I tried other tools for logging in and they are also now broken. Will wait for a consensus from other devs as I don't see a clear way to fix this yet.

https://github.com/adriankumpf/teslamate/issues/1398

**Comment by uhthomas** [comment] 2021-02-25 23:53
Also see https://github.com/uhthomas/tesla/issues/5#issuecomment-786309298

**Comment by bogosj** [comment] 2021-02-26 00:08
Thanks @uhthomas. I was discussing with @michaelharo about possibly pulling cmd/login into https://github.com/bogosj/tesla and applying these conceptual changes. Any interest in joining efforts on this and living there?

**Comment by uhthomas** [comment] 2021-02-26 00:10
Yep, am happy to do that and be an active contributor for your repository.

**Comment by bogosj** [comment] 2021-02-26 00:14
Fabulous. I'll send an invite to contribute and I'll put together a PR for "forking" cmd/login over for you to review. Happy to shoulder that since you did most of the heavy lifting already.

**Comment by bogosj** [comment] 2021-02-26 01:52
https://github.com/bogosj/tesla/pull/21 - There's some lint/staticheck/errcheck warnings that I'm going to ignore from now. We'll eventually do a full pass of the library for all of that.

**Comment by uhthomas** [comment] 2021-02-26 20:31
Going to close this for now as we seem to have come to a consensus on the direction of packages and such. Thanks both.

**Closed by uhthomas** 2021-02-26 20:31 UTC

**Comment by andig** [comment] 2021-02-26 20:47
Thank you for the journey sofar 🔝
